### ISSUE TITLE
Using parameters from the user in the desktop templates

### ISSUE THREAD

**Issue by hananmoiseyev** [tinyzimmer/kvdi#23]
Hi,

To avoid creating a template for each user, I would like to use the user name as a parameter in the templates. Is that possible?

**Comment by tinyzimmer** [comment]
What specifically do you mean by a "parameter"? If you mean like environment variables, this is actually possible because of what I did for #19. You'd use the new `envTemplates` field with something like this:

```yaml
spec:
  desktop:
    envTemplates:
      USERNAME: "{{ .Session.User.Name }}"
```
